name: Metrics.png

concurrency:
  group: metrics-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  github-metrics-png:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: refs/heads/main
      - name: "metrics 1"
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: none
          config_output: png
          filename: metrics-1.png
          config_presets: https://raw.githubusercontent.com/H1rono/H1rono/main/metrics-presets/preset-1.yml
      - name: "metrics 2"
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: none
          config_output: png
          filename: metrics-2.png
          config_presets: https://raw.githubusercontent.com/H1rono/H1rono/main/metrics-presets/preset-2.yml
      - name: "collect metrics images"
        run: |
          mkdir tmp
          sudo cp /metrics_renders/metrics-1.png ./tmp/
          sudo cp /metrics_renders/metrics-2.png ./tmp/
          sudo chown -R "$USER:$USER" tmp
          sudo chmod 644 tmp/*.png
          mv tmp/metrics-1.png assets/
          mv tmp/metrics-2.png assets/
      - name: "commit metrics updates"
        run: bash .github/scripts/push-assets.bash
